Denis Wilfredo Lopez Ortega/Denis Wilfredo Lopez Ortega/Models/ViewModel/CajeroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Denis_Wilfredo_Lopez_Ortega.Models.ViewModel
{
    public class CajeroViewModel
    {
        [Display(Name = "Monto")]
        [Required(ErrorMessage ="Este campo es requerido")]
        public int Monto {get; set;}
    }
}

Denis Wilfredo Lopez Ortega/Denis Wilfredo Lopez Ortega/Controllers/CajeroController.cs
using Denis_Wilfredo_Lopez_Ortega.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Denis_Wilfredo_Lopez_Ortega.Controllers
{
    public class CajeroController : Controller
    {
        
        // GET: Cajero
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult Permitido()
        {

            return View();
        }

        public ActionResult Error()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Comprobacion(CajeroViewModel cajero)
        {
            if (cajero.Monto%5==0)
            {
                
                return RedirectToAction("Permitido");
            }
            else
            {
                return RedirectToAction("Error");
            }
            
        }
    }
}

Denis Wilfredo Lopez Ortega/Denis Wilfredo Lopez Ortega/Views/Cajero/Index.cshtml
@model Denis_Wilfredo_Lopez_Ortega.Models.ViewModel.CajeroViewModel
@{
    ViewBag.Title = "Index";
}
<h2>Cajero Automatico</h2>

@using (Html.BeginForm("Comprobacion", "Cajero", FormMethod.Post))
{
    <label>Monto a retirar</label>
    <br />
    <br />
    @Html.TextBoxFor(m => m.Monto, new { required = "required", type = "number" })

    <br />
    <br />
    <input type="submit" />
}

Denis Wilfredo Lopez Ortega/Denis Wilfredo Lopez Ortega/Views/Cajero/Permitido.cshtml
@{
    ViewBag.Title = "Permitido";
}

<h2>Puedes retirar tu dinero</h2>

Denis Wilfredo Lopez Ortega/Denis Wilfredo Lopez Ortega/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cajero", "Index", "Cajero", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>